
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-flask1
  name: hello-world-flask1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-flask
  template:
    metadata:
      labels:
        app: hello-world-flask
    spec:
      containers:
      - image: lyzhang1999/hello-world-flask:latest
        name: hello-world-flask1